### ISSUE TITLE
Post templates are not working as they supposed too.

### ISSUE THREAD

**Issue by hamzamu** [godofredoninja/simply#116]
It is a good theme, but the post templates are not working as they supposed to

![Screen Shot 2022-04-09 at 12 44 17](https://user-images.githubusercontent.com/340579/162566642-2c966f28-d28c-4e69-b876-77cfba4d0db9.png)

**Comment by hamzamu** [comment]
I disabled the `godo-canvas` and rebuilding the post.hbs page and templates. It works fine on the local host but messed up on the server.

**Comment by godofredoninja** [comment]
Hi

I just checked and what happens is the following

in your style file comes as follows.

the grid is with a b/c

```css
.godo-canvas>* {
    grid-column: b/c;
}
```

The right thing to do has to be as here.

```css
.godo-canvas>* {
    grid-column:main-start/main-end
}
```

This could solve the problem.... Add it in your ghost configuration in the code section.

```html
<style>
  .godo-canvas>*{grid-column:main-start/main-end}
  .is-canvas-full .godo-canvas>*{grid-column:full-start/full-end}
</style>
```
