### ISSUE TITLE
Show Posts on the Portfolio to the homepage

### ISSUE THREAD

**Issue by TruongNguyen5395** [godofredoninja/simply#181]
Hi,

I'm applying the Portfolio in my routes setting but when this feature applies all the post just show on the Portfolio section. Can we setting the routes file to make these Post also show on the homepage?

**Comment by godofredoninja** [comment]
Hi

Next time share your code to help you faster... we save time for you and me.

😃 

```yaml
routes:
  /:
    controller: channel
    permalink: /{slug}/
    template: godo-template-medium
    limit: 14

collections:
# PortFolio
  /portafolio/:
    permalink: /portafolio/{slug}/
    filter: 'tag:[hash-portfolio]'
    data: page.porftfolio
    template: godo-template-portfolio
    limit: all

  /:
    permalink: /{slug}/
    template: godo-template-medium
    limit: 14

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```
