### ISSUE TITLE
[BUG] assets url incorrect if using sub folder base URL

### ISSUE THREAD

**Issue by soakes** [godofredoninja/simply#24]
Hi there,

It seems I have stumbled on a bug with your awesome theme.

I have my site hosted with the following URL: https://example.com/blog and not https://example.com.

This is set via URL environment var with the official ghost docker image.

Now I found the social icons were missing for some reason so I tested the git version and a few other releases but they all suffered the same thing.  So I decided to poke around the code using devloper console in firefox and noticed some errors.

```
downloadable font: download failed (font-family: "simply" style:normal weight:normal stretch:normal src index:1): status=2147746065 source: https://example.com/assets/fonts/simply.ttf unknown:1:25335
downloadable font: download failed (font-family: "simply" style:normal weight:normal stretch:normal src index:2): status=2147746065 source: https://example.com/assets/fonts/simply.woff
```

These URLs should really be: https://example.com/blog/assets/fonts/simply.woff

Is there a simple way to make this theme compatible with sub folder base urls? or should I just do a search and replace on the code which seems wrong?

Maybe some kinda global could be added to adjust the baseurl? or read the header?

Below is my docker stack file.

```
---
version: '3.4'

networks:
  backend:
    external: true

#
# Ghost Blog (https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables)
# Port: 2368
#

services:
  blog:
    image: ghost:1-alpine
    networks:
      backend:
        aliases:
          - example_blog
    volumes:
      - /var/lib/docker/ceph/volumes/example_blog/content:/var/lib/ghost/content
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: example_blog
      database__connection__password: ****************
      database__connection__database: example_blog
      url: https://example.com/blog
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == worker
```
