### ISSUE TITLE
Theme change issue

### ISSUE THREAD

**Issue by AnkitMaheshwariIn** [godofredoninja/simply#44]
Hello, thanks for nice theme.

I could not see change reflect in my website after changing the theme. It still shows index theme even after changing to 'godo-template-sidebar'.

Please check, this is the change I made:

collections:
  /:
    permalink: /{slug}/
    template: godo-template-sidebar

**Comment by godofredoninja** [comment]
## Hello  :smile: 

It's all good. I think your server needs to be refreshed

`ghost restart`

```yaml
collections:
  /:
    permalink: /{slug}/
    template: godo-template-sidebar
```
