### ISSUE TITLE
Exclude Posts from specific tag on Homepage

### ISSUE THREAD

**Issue by geetansh** [godofredoninja/simply#58]
Hi,
Thanks for your amazing work first of all.
I am trying to exclude posts from specific tag on homepage, I have tried following fix but no success

File: index.hbs (theme folder)

```javascript
   {{#get "posts" filter="tags:-[ShortNews,shortnews]"}}
	    {{#foreach posts visibility="all"}}
        {{/foreach}}
    {{/get}}
```

```javascript
   {{#get "posts" filter="tags:-[ShortNews,shortnews]"}}
	    {{#foreach posts}}
        {{/foreach}}
    {{/get}}
```

**Comment by godofredoninja** [comment]
Hi

To exclude publications it is not necessary to touch the code of simply. this can be done by means of the [routes collection](https://ghost.org/docs/api/v3/handlebars-themes/routing/collections/).

First, configure your routes.yaml file to exclude tags. Download your routes.yaml file from the Labs view inside the Ghost manager and open it with any code editor.

The following example shows how to set up a collection to exclude a label. 

```yaml
routes:

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: 'tag:-[shortnews]'

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```

**Comment by geetansh** [comment]
Hi,
Thanks for the Update.
Using this method, I am able to exclude the post from Homepage but on tag page post is redirecting to 404.

Example:
I have created a post with URL - https://domain.com/this-is-special-tag-post-url
and set the required tag

Now post is visible on that tag page only : https://domain.com/tag/special-tag
but when i hover cursor on post, URL is different - https://domain.com/p/69b7bbd3-0b94-4f4e-b0ef-e6fa577473e9/ 

and when i click the post i get reidrected to 404 page

**Comment by godofredoninja** [comment]
Hello.

I think you want to do something similar to this.

**This is the behavior of a normal tag**
- Appears on: `site.com/tag/blog/`
- Post URLs: `site.com/my-story/`
- Contains posts with: a `primary_tag` of `blog`

**But what you want to get this**
- Appears on: `site.com/blog/`
- Post URLs: `site.com/blog/my-story/`
- Contains posts with: a `primary_tag` of `blog`

```yaml
collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index
    filter: primary_tag:blog
    data: tag.blog
```

Here in the [ghost documentation ](https://ghost.org/docs/api/v3/handlebars-themes/routing/collections/#loading-data-into-the-index)they explain how to do that.
