### ISSUE TITLE
Special Tag Pages

### ISSUE THREAD

**Issue by Ingles-con-Kip** [godofredoninja/simply#91]
Hello. 

In the example site godofredo.ninja, clicking a tag link in the tag archive page takes you to a collection with a basic grey header. For example, if I'm at https://godofredo.ninja/tags/ and I click "Actualidad" the header reads: 

### Actualidad
Inicio > Tag "Actualidad" and the url is https://godofredo.ninja/tag/actualidad/

However, if I click on "Juegos" or "Amor & Relación", for example, the subsequent page has a designed header with a description and an image and the url is different from the other tag links, for example, https://godofredo.ninja/amor-relacion/

I can't seem to find out how to achieve this result in the documentation. I don't know if this constitutes an issue or not but any help would be appreciated. 

Great work by the way. This is a really nice theme.

**Comment by godofredoninja** [comment]
Hi @Ingles-con-Kip 

If you want to have something similar to mine then you have to create a custom template.

And then use the Ghost routes.

For example my route:

```yaml
routes:

  /amor-relacion/:
    controller: channel
    filter: tag:amor-relacion
    limit: 12
    template: godo-template-category
    data: tag.amor-relacion
```

In this ` /amor-relacion/` path I have created a template called `godo-template-category` and I am filtering it all the articles from the tag `amor-relacion` and also the tag data like image description and name.
