### ISSUE TITLE
How to have the portfolio page as the main page?

### ISSUE THREAD

**Issue by jotcodeofficial** [godofredoninja/simply#96]
Hi, love the theme.

How can I have the portfolio as the main page, and have the blog on domain.com/blog
Thanks!

**Comment by godofredoninja** [comment]
Hello, how are you?

Its very easy

Work with the [routes - collection](https://ghost.org/docs/themes/routing/).

👉 To set the portfolio Page follow the steps below.

- Create a new page
- Choose your favorite title
- Use the URL `portfolio`
- Choose your favorite description in excerpt
- Use all tags to filter all portfolios

https://godofredo.ninja/ghost-theme/simply/portfolio/

👉 Portfolio collection

for example:

```yaml
routes:

collections:
  # Blog
  /blog/:
    permalink: /blog/{slug}/
    filter: 'tag:-[hash-portfolio]'
    template: index

  # Portfolio
  /:
    permalink: /portfolio/{slug}/
    filter: 'tag:[hash-portfolio]'
    data: page.porftfolio
    template: godo-template-portfolio
    limit: all

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/

```
